export enum SystemPermission {
  MEMBER_VIEW = 'MEMBER_VIEW',
  MEMBER_CREATE = 'MEMBER_CREATE',
  MEMBER_UPDATE = 'MEMBER_UPDATE',
  MEMBER_DELETE = 'MEMBER_DELETE',
  MEMBER_APPROVE = 'MEMBER_APPROVE',

  DISTRICT_VIEW = 'DISTRICT_VIEW',
  DISTRICT_CREATE = 'DISTRICT_CREATE',
  DISTRICT_UPDATE = 'DISTRICT_UPDATE',
  DISTRICT_DELETE = 'DISTRICT_DELETE',

  COMMITTEE_VIEW = 'COMMITTEE_VIEW',
  COMMITTEE_CREATE = 'COMMITTEE_CREATE',
  COMMITTEE_UPDATE = 'COMMITTEE_UPDATE',
  COMMITTEE_DELETE = 'COMMITTEE_DELETE',

  ROLE_VIEW = 'ROLE_VIEW',
  ROLE_CREATE = 'ROLE_CREATE',
  ROLE_UPDATE = 'ROLE_UPDATE',
  ROLE_DELETE = 'ROLE_DELETE',

  PERMISSION_VIEW = 'PERMISSION_VIEW',
  PERMISSION_CREATE = 'PERMISSION_CREATE',
  PERMISSION_UPDATE = 'PERMISSION_UPDATE',
  PERMISSION_DELETE = 'PERMISSION_DELETE',

  WORKFLOW_VIEW = 'WORKFLOW_VIEW',
  WORKFLOW_APPROVE = 'WORKFLOW_APPROVE',
  WORKFLOW_REJECT = 'WORKFLOW_REJECT',

  AUDIT_VIEW = 'AUDIT_VIEW',

  FILE_UPLOAD = 'FILE_UPLOAD',
  FILE_DELETE = 'FILE_DELETE',

  NOTIFICATION_SEND = 'NOTIFICATION_SEND',

  SETTINGS_VIEW = 'SETTINGS_VIEW',
  SETTINGS_UPDATE = 'SETTINGS_UPDATE',
}
