export enum SystemRole {
  SUPER_ADMIN = 'SUPER_ADMIN',
  STATE_ADMIN = 'STATE_ADMIN',
  STATE_SECRETARY = 'STATE_SECRETARY',
  DISTRICT_ADMIN = 'DISTRICT_ADMIN',
  DISTRICT_SECRETARY = 'DISTRICT_SECRETARY',
  MEMBER = 'MEMBER',
}
