import { PERMISSIONS } from './permissions';

import type { Permission } from './permissions';

/**
 * Enterprise RBAC Permission Groups
 *
 * A Permission Group represents a reusable collection of
 * low-level permissions.
 *
 * Role Profiles reference Permission Groups rather than
 * individual permissions to simplify maintenance.
 *
 * Hierarchy:
 *
 * Permission
 *      ↓
 * Permission Group
 *      ↓
 * Role Profile
 *      ↓
 * Role
 */
export const PERMISSION_GROUPS = {
  MEMBER_MANAGEMENT: [
    PERMISSIONS.MEMBER.READ,
    PERMISSIONS.MEMBER.CREATE,
    PERMISSIONS.MEMBER.UPDATE,
    PERMISSIONS.MEMBER.DELETE,
    PERMISSIONS.MEMBER.APPROVE,
    PERMISSIONS.MEMBER.VERIFY,
    PERMISSIONS.MEMBER.EXPORT,
  ],

  APPLICATION_MANAGEMENT: [
    PERMISSIONS.APPLICATION.SUBMIT,
    PERMISSIONS.APPLICATION.REVIEW,
    PERMISSIONS.APPLICATION.APPROVE,
    PERMISSIONS.APPLICATION.REJECT,
    PERMISSIONS.APPLICATION.ASSIGN,
  ],

  DISTRICT_MANAGEMENT: [
    PERMISSIONS.DISTRICT.READ,
    PERMISSIONS.DISTRICT.CREATE,
    PERMISSIONS.DISTRICT.UPDATE,
    PERMISSIONS.DISTRICT.DELETE,
    PERMISSIONS.DISTRICT.MANAGE,
  ],

  COMMITTEE_MANAGEMENT: [
    PERMISSIONS.COMMITTEE.READ,
    PERMISSIONS.COMMITTEE.CREATE,
    PERMISSIONS.COMMITTEE.UPDATE,
    PERMISSIONS.COMMITTEE.DELETE,
    PERMISSIONS.COMMITTEE.MANAGE,
  ],

  MEETING_MANAGEMENT: [
    PERMISSIONS.MEETING.READ,
    PERMISSIONS.MEETING.CREATE,
    PERMISSIONS.MEETING.UPDATE,
    PERMISSIONS.MEETING.DELETE,
    PERMISSIONS.MEETING.MANAGE,
  ],

  EVENT_MANAGEMENT: [
    PERMISSIONS.EVENT.READ,
    PERMISSIONS.EVENT.CREATE,
    PERMISSIONS.EVENT.UPDATE,
    PERMISSIONS.EVENT.DELETE,
    PERMISSIONS.EVENT.PUBLISH,
  ],

  PAYMENT_MANAGEMENT: [
    PERMISSIONS.PAYMENT.READ,
    PERMISSIONS.PAYMENT.CREATE,
    PERMISSIONS.PAYMENT.VERIFY,
    PERMISSIONS.PAYMENT.APPROVE,
    PERMISSIONS.PAYMENT.REFUND,
  ],

  CERTIFICATE_MANAGEMENT: [
    PERMISSIONS.CERTIFICATE.READ,
    PERMISSIONS.CERTIFICATE.GENERATE,
    PERMISSIONS.CERTIFICATE.REVOKE,
    PERMISSIONS.CERTIFICATE.VERIFY,
  ],

  DOCUMENT_MANAGEMENT: [
    PERMISSIONS.DOCUMENT.READ,
    PERMISSIONS.DOCUMENT.CREATE,
    PERMISSIONS.DOCUMENT.UPDATE,
    PERMISSIONS.DOCUMENT.DELETE,
    PERMISSIONS.DOCUMENT.DOWNLOAD,
  ],

  REPORT_MANAGEMENT: [
    PERMISSIONS.REPORT.VIEW,
    PERMISSIONS.REPORT.EXPORT,
  ],

  NOTIFICATION_MANAGEMENT: [
    PERMISSIONS.NOTIFICATION.READ,
    PERMISSIONS.NOTIFICATION.SEND,
    PERMISSIONS.NOTIFICATION.MANAGE,
  ],

  CMS_MANAGEMENT: [
    PERMISSIONS.CMS.READ,
    PERMISSIONS.CMS.CREATE,
    PERMISSIONS.CMS.UPDATE,
    PERMISSIONS.CMS.DELETE,
    PERMISSIONS.CMS.PUBLISH,
  ],

  USER_MANAGEMENT: [
    PERMISSIONS.USER.READ,
    PERMISSIONS.USER.CREATE,
    PERMISSIONS.USER.UPDATE,
    PERMISSIONS.USER.DELETE,
    PERMISSIONS.USER.MANAGE,
  ],

  ROLE_MANAGEMENT: [
    PERMISSIONS.ROLE.READ,
    PERMISSIONS.ROLE.CREATE,
    PERMISSIONS.ROLE.UPDATE,
    PERMISSIONS.ROLE.DELETE,
    PERMISSIONS.ROLE.ASSIGN,
  ],

  SETTINGS_MANAGEMENT: [
    PERMISSIONS.SETTINGS.READ,
    PERMISSIONS.SETTINGS.UPDATE,
    PERMISSIONS.SETTINGS.MANAGE,
  ],

  AUDIT_MANAGEMENT: [
    PERMISSIONS.AUDIT.VIEW,
    PERMISSIONS.AUDIT.EXPORT,
  ],
} satisfies Record<
  string,
  readonly Permission[]
>;

/**
 * Prevent runtime mutation of the permission catalog.
 */
Object.freeze(PERMISSION_GROUPS);

/**
 * All valid Permission Group identifiers.
 */
export type PermissionGroup =
  keyof typeof PERMISSION_GROUPS;
