export const ROLE_LEVELS = {
  SUPER_ADMIN: 100,

  PLATFORM_ADMIN: 95,

  STATE_PRESIDENT: 90,
  STATE_GENERAL_SECRETARY: 89,
  STATE_SECRETARY: 88,
  STATE_TREASURER: 87,
  STATE_VICE_PRESIDENT: 86,
  STATE_EXECUTIVE_MEMBER: 80,

  DISTRICT_PRESIDENT: 70,
  DISTRICT_SECRETARY: 69,
  DISTRICT_TREASURER: 68,
  DISTRICT_VICE_PRESIDENT: 67,
  DISTRICT_EXECUTIVE_MEMBER: 60,

  COMMITTEE_CONVENOR: 50,
  COMMITTEE_JOINT_CONVENOR: 49,
  COMMITTEE_MEMBER: 40,

  AUDITOR: 35,
  RETURNING_OFFICER: 34,
  ELECTION_OFFICER: 33,

  MEMBER: 20,
  APPLICANT: 10,
  PUBLIC: 0,
} as const;

export type RoleLevel = (typeof ROLE_LEVELS)[keyof typeof ROLE_LEVELS];
